"""Streamlit dashboard for the financial sentiment classification project.

Two tabs:
- Live Demo: type/pick a financial sentence, see all four models' predictions side by side.
- Results Dashboard: the precomputed comparison table, figures, and significance test from
  results/ (generated by notebooks/report.ipynb) presented for a walkthrough/presentation.

Run with: streamlit run app.py
"""

import sys
import textwrap
from pathlib import Path

import pandas as pd
import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parent
SRC_PATH = PROJECT_ROOT / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from finsent.config import CONFIG, resolve_path  # noqa: E402
from finsent.palette import (  # noqa: E402
    BASELINE,
    BORDER,
    GRIDLINE,
    MODEL_COLORS,
    PAGE_PLANE,
    SENTIMENT_COLORS,
    SURFACE,
    TEXT_MUTED,
    TEXT_PRIMARY,
    TEXT_SECONDARY,
    model_color,
    sentiment_color,
)

st.set_page_config(page_title="Financial Sentiment Classification", page_icon="📈", layout="wide")

MODEL_DESCRIPTIONS = {
    "VADER": "General-purpose lexicon tuned on social media text.",
    "Loughran-McDonald": "Finance-specific word lists built for 10-K/10-Q filing language.",
    "TF-IDF + ML": "Supervised Logistic Regression / Linear SVM trained on labeled financial sentences.",
    "FinBERT (zero-shot)": "Pretrained transformer, used as-is (no fine-tuning), for reference.",
}

EXAMPLE_SENTENCES = {
    "-- pick an example --": "",
    "Clearly positive": "The company reported record profit and strong revenue growth this quarter.",
    "Clearly negative": "The company posted a significant loss amid declining sales and rising costs.",
    "Hedged / neutral (the hard case)": "The company plans to spend the proceeds from the rights offering for strengthening its balance sheet.",
    "Factual, no real sentiment": "The annual general meeting will be held in Helsinki on March 15.",
}


# ---------------------------------------------------------------------------
# Design system: CSS custom properties + component classes, mirroring finsent.palette
# ---------------------------------------------------------------------------

def inject_css():
    css = f"""
        <style>
        :root {{
            --surface-1: {SURFACE};
            --page-plane: {PAGE_PLANE};
            --text-primary: {TEXT_PRIMARY};
            --text-secondary: {TEXT_SECONDARY};
            --text-muted: {TEXT_MUTED};
            --gridline: {GRIDLINE};
            --baseline: {BASELINE};
            --border: {BORDER};
        }}

        .stApp {{ background-color: var(--page-plane); }}

        h1, h2, h3 {{ color: var(--text-primary); font-weight: 700; }}
        p, li, label {{ color: var(--text-secondary); }}

        /* Stat tiles */
        .tile-row {{ display: flex; gap: 14px; margin: 4px 0 22px 0; flex-wrap: wrap; }}
        .stat-tile {{
            flex: 1; min-width: 190px; background: var(--surface-1);
            border: 1px solid var(--border); border-radius: 10px;
            padding: 14px 18px;
        }}
        .stat-tile .tile-label {{
            font-size: 12.5px; color: var(--text-muted); margin-bottom: 6px;
        }}
        .stat-tile .tile-value {{
            font-size: 26px; font-weight: 700; color: var(--text-primary); line-height: 1.15;
        }}
        .stat-tile .tile-sub {{
            font-size: 12px; color: var(--text-secondary); margin-top: 4px;
        }}

        /* Sentiment badges */
        .sentiment-badge {{
            display: inline-block; padding: 3px 12px; border-radius: 999px;
            font-weight: 700; font-size: 12px; letter-spacing: 0.03em;
            text-transform: uppercase; color: #ffffff;
        }}

        /* Live-demo model comparison rows */
        .model-card {{
            background: var(--surface-1); border: 1px solid var(--border);
            border-radius: 10px; padding: 14px 18px; margin-bottom: 10px;
        }}
        .model-card .model-row {{ display: flex; align-items: center; gap: 16px; }}
        .model-card .model-name {{
            flex: 0 0 190px; font-weight: 600; color: var(--text-primary); font-size: 14.5px;
        }}
        .model-card .model-desc {{
            font-size: 12px; color: var(--text-muted); margin-top: 4px;
        }}
        .meter-wrap {{ flex: 1; display: flex; align-items: center; gap: 10px; }}
        .meter-track {{
            flex: 1; height: 9px; border-radius: 5px; overflow: hidden;
        }}
        .meter-fill {{ height: 100%; border-radius: 5px; }}
        .meter-pct {{ font-size: 12.5px; color: var(--text-secondary); width: 42px; text-align: right; }}
        .model-unavailable {{ color: var(--text-muted); font-size: 13px; font-style: italic; }}

        /* Agreement banner */
        .agreement-banner {{
            border-radius: 8px; padding: 10px 16px; margin: 6px 0 18px 0;
            font-size: 14px; font-weight: 600; border-left: 4px solid;
        }}

        /* Sidebar glossary */
        .glossary-item {{ margin-bottom: 10px; }}
        .glossary-item .g-name {{ font-weight: 700; font-size: 13px; color: var(--text-primary); }}
        .glossary-item .g-desc {{ font-size: 12.5px; color: var(--text-secondary); }}
        </style>
        """
    # Streamlit's markdown renderer treats a 4-space-indented line as a code block,
    # which would otherwise swallow this whole block as literal text instead of real CSS.
    st.markdown(textwrap.dedent(css).strip(), unsafe_allow_html=True)


def sentiment_badge_html(label: str) -> str:
    color = sentiment_color(label)
    return f'<span class="sentiment-badge" style="background:{color}">{label}</span>'


# NOTE: every *_html builder below returns a single flat line with no embedded
# newlines or leading whitespace. Streamlit's markdown renderer treats a 4-space
# indented line as a Markdown code block, which silently swallows nested HTML
# (e.g. the meter bar) as literal text instead of rendering it — multi-line
# pretty-printed f-strings trip this even though a lone flat <div> does not.

def stat_tile_html(label: str, value: str, sub: str = "") -> str:
    sub_html = f'<div class="tile-sub">{sub}</div>' if sub else ""
    return (
        '<div class="stat-tile">'
        f'<div class="tile-label">{label}</div>'
        f'<div class="tile-value">{value}</div>'
        f'{sub_html}'
        '</div>'
    )


def model_card_html(display_name: str, label: str, proba: dict) -> str:
    color = sentiment_color(label)
    desc = MODEL_DESCRIPTIONS.get(display_name, "")
    if proba:
        pct = proba.get(label, 0.0) * 100
        meter = (
            '<div class="meter-wrap">'
            f'<div class="meter-track" style="background:{color}22">'
            f'<div class="meter-fill" style="width:{pct:.0f}%; background:{color}"></div>'
            '</div>'
            f'<div class="meter-pct">{pct:.0f}%</div>'
            '</div>'
        )
    else:
        meter = '<div class="meter-wrap"><span class="model-unavailable">no confidence score available</span></div>'

    return (
        '<div class="model-card">'
        '<div class="model-row">'
        f'<div class="model-name">{display_name}</div>'
        f'{sentiment_badge_html(label)}'
        f'{meter}'
        '</div>'
        f'<div class="model-desc">{desc}</div>'
        '</div>'
    )


def unavailable_card_html(display_name: str, error: str) -> str:
    desc = MODEL_DESCRIPTIONS.get(display_name, "")
    return (
        '<div class="model-card">'
        '<div class="model-row">'
        f'<div class="model-name">{display_name}</div>'
        f'<span class="model-unavailable">unavailable — {error}</span>'
        '</div>'
        f'<div class="model-desc">{desc}</div>'
        '</div>'
    )


# ---------------------------------------------------------------------------
# Model loading (cached)
# ---------------------------------------------------------------------------

@st.cache_resource(show_spinner="Loading VADER...")
def load_vader():
    from finsent.models.vader_model import VaderModel
    return VaderModel()


@st.cache_resource(show_spinner="Loading Loughran-McDonald lexicon...")
def load_lm():
    from finsent.models.loughran_mcdonald import LoughranMcDonaldModel
    return LoughranMcDonaldModel()


@st.cache_resource(show_spinner="Loading TF-IDF+ML pipeline...")
def load_tfidf_ml():
    from finsent.models.tfidf_ml import TfidfMlModel
    model = TfidfMlModel()
    return model.load()


@st.cache_resource(show_spinner="Loading FinBERT (first load can take ~20s)...")
def load_finbert():
    from finsent.models.finbert_model import FinBertModel
    return FinBertModel()


def try_load(loader):
    try:
        return loader(), None
    except Exception as e:
        return None, str(e)


# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------

def render_sidebar():
    with st.sidebar:
        st.markdown("### 📈 About this project")
        st.markdown(
            "Comparing lexicon-based and machine-learning approaches to sentiment "
            "classification on financial text, using the Financial PhraseBank dataset."
        )
        st.markdown("---")
        st.markdown("### Models compared")
        for name, desc in MODEL_DESCRIPTIONS.items():
            color = model_color(name)
            st.markdown(
                '<div class="glossary-item">'
                f'<div class="g-name" style="border-left:3px solid {color}; padding-left:8px;">{name}</div>'
                f'<div class="g-desc" style="padding-left:11px;">{desc}</div>'
                '</div>',
                unsafe_allow_html=True,
            )
        st.markdown("---")
        st.caption(
            "Loughran-McDonald requires the manually downloaded dictionary at "
            "`data/external/LM_MasterDictionary.csv`. TF-IDF+ML requires having run "
            "the report notebook at least once."
        )


# ---------------------------------------------------------------------------
# Live Demo tab
# ---------------------------------------------------------------------------

def live_demo_tab():
    st.markdown("#### Classify a financial sentence with all four models")

    example_key = st.selectbox("Example sentences", list(EXAMPLE_SENTENCES.keys()))
    default_text = EXAMPLE_SENTENCES[example_key]
    sentence = st.text_area(
        "Sentence", value=default_text, height=90,
        placeholder="e.g. Operating margin improved despite a challenging market.",
    )

    if st.button("Classify", type="primary") and sentence.strip():
        vader, vader_err = try_load(load_vader)
        lm, lm_err = try_load(load_lm)
        tfidf_ml, tfidf_err = try_load(load_tfidf_ml)
        finbert, finbert_err = try_load(load_finbert)

        model_specs = [
            ("VADER", vader, vader_err),
            ("Loughran-McDonald", lm, lm_err),
            ("TF-IDF + ML", tfidf_ml, tfidf_err),
            ("FinBERT (zero-shot)", finbert, finbert_err),
        ]

        labels_seen = []
        cards_html = []
        for display_name, model, err in model_specs:
            if err:
                cards_html.append(unavailable_card_html(display_name, err))
                continue
            label = model.predict([sentence])[0]
            proba = model.predict_proba([sentence])
            proba = proba[0] if proba else None
            labels_seen.append(label)
            cards_html.append(model_card_html(display_name, label, proba))

        if labels_seen:
            unique_labels = set(labels_seen)
            if len(unique_labels) == 1:
                good = sentiment_color(labels_seen[0])
                st.markdown(
                    f'<div class="agreement-banner" style="background:{good}14; '
                    f'border-color:{good}; color:{good}">'
                    f'✓ All {len(labels_seen)} available models agree: {labels_seen[0].upper()}</div>',
                    unsafe_allow_html=True,
                )
            else:
                counts = pd.Series(labels_seen).value_counts()
                summary = ", ".join(f"{c} say {lbl}" for lbl, c in counts.items())
                st.markdown(
                    f'<div class="agreement-banner" style="background:#fab21914; '
                    f'border-color:#fab219; color:{TEXT_PRIMARY}">'
                    f"⚠ Models disagree — {summary}</div>",
                    unsafe_allow_html=True,
                )

        st.markdown("".join(cards_html), unsafe_allow_html=True)


# ---------------------------------------------------------------------------
# Results Dashboard tab
# ---------------------------------------------------------------------------

def render_stat_tiles(comparison_df: pd.DataFrame, significance_df: pd.DataFrame | None):
    best_acc_row = comparison_df.loc[comparison_df["accuracy"].idxmax()]
    best_f1_row = comparison_df.loc[comparison_df["macro_f1"].idxmax()]
    best_neutral_row = comparison_df.loc[comparison_df["neutral_f1"].idxmax()]
    baseline_row = comparison_df.loc[comparison_df["macro_f1"].idxmin()]

    lift = best_f1_row["macro_f1"] - baseline_row["macro_f1"]

    if significance_df is not None and len(significance_df):
        n_sig = int(significance_df["significant"].sum())
        n_total = len(significance_df)
        sig_value = f"{n_sig}/{n_total}"
        sig_sub = "pairwise comparisons (McNemar's test)"
    else:
        sig_value, sig_sub = "—", "run the notebook to compute"

    tiles = "".join([
        stat_tile_html("Best accuracy", f'{best_acc_row["accuracy"]:.1%}', best_acc_row["model"]),
        stat_tile_html("Best macro-F1", f'{best_f1_row["macro_f1"]:.3f}', best_f1_row["model"]),
        stat_tile_html("Best neutral-class F1", f'{best_neutral_row["neutral_f1"]:.3f}', best_neutral_row["model"]),
        stat_tile_html("Macro-F1 lift, best vs. weakest", f"+{lift:.3f}",
                        f'{baseline_row["model"]} → {best_f1_row["model"]}'),
        stat_tile_html("Statistically significant", sig_value, sig_sub),
    ])
    st.markdown(f'<div class="tile-row">{tiles}</div>', unsafe_allow_html=True)


def results_dashboard_tab():
    st.caption("Generated by notebooks/report.ipynb — rerun it to refresh these after any changes.")

    tables_dir = resolve_path(CONFIG["results"]["tables_dir"])
    figures_dir = resolve_path(CONFIG["results"]["figures_dir"])

    comparison_path = tables_dir / "comparison.csv"
    if not comparison_path.exists():
        st.info("No results yet — run notebooks/report.ipynb first to generate them.")
        return

    comparison_df = pd.read_csv(comparison_path)
    significance_path = tables_dir / "significance.csv"
    significance_df = pd.read_csv(significance_path) if significance_path.exists() else None

    render_stat_tiles(comparison_df, significance_df)

    st.markdown("#### Model comparison")
    st.dataframe(
        comparison_df.style.format({
            "accuracy": "{:.1%}", "macro_precision": "{:.3f}", "macro_recall": "{:.3f}",
            "macro_f1": "{:.3f}", "neutral_f1": "{:.3f}",
        }).background_gradient(subset=["macro_f1"], cmap="Blues"),
        use_container_width=True, hide_index=True,
    )

    comparison_chart = figures_dir / "comparison.png"
    if comparison_chart.exists():
        st.image(str(comparison_chart))

    if significance_df is not None:
        st.markdown("#### Statistical significance")
        n_sig = int(significance_df["significant"].sum())
        st.caption(
            f"McNemar's exact test, pairwise on the shared test set — "
            f"{n_sig} of {len(significance_df)} pairwise differences are significant at p < 0.05."
        )
        display_sig = significance_df.copy()
        display_sig["p_value"] = display_sig["p_value"].apply(lambda p: f"{p:.2e}")
        st.dataframe(display_sig, use_container_width=True, hide_index=True)

    st.markdown("#### Confusion matrices")
    model_names = comparison_df["model"].tolist()
    cols = st.columns(2)
    for i, name in enumerate(model_names):
        safe_name = name.replace(" ", "_").replace("(", "").replace(")", "")
        cm_path = figures_dir / f"{safe_name}_confusion.png"
        if cm_path.exists():
            cols[i % 2].image(str(cm_path), use_container_width=True)

    hardest_path = tables_dir / "hardest_sentences.csv"
    if hardest_path.exists():
        st.markdown("#### Hardest sentences (wrong on 2+ models)")
        hardest_df = pd.read_csv(hardest_path)
        pred_cols = [c for c in hardest_df.columns if c.startswith("pred_")]
        display_cols = ["sentence", "true_label", "n_models_wrong"] + pred_cols
        column_config = {
            "sentence": st.column_config.TextColumn("Sentence", width="large"),
            "true_label": st.column_config.TextColumn("True", width="small"),
            "n_models_wrong": st.column_config.NumberColumn("# wrong", width="small"),
        }
        for c in pred_cols:
            column_config[c] = st.column_config.TextColumn(c.replace("pred_", ""), width="small")
        st.dataframe(
            hardest_df[display_cols].head(15), use_container_width=True,
            hide_index=True, column_config=column_config,
        )


# ---------------------------------------------------------------------------
# Layout
# ---------------------------------------------------------------------------

inject_css()
render_sidebar()

st.title("Lexicon-Based vs. Machine Learning Approaches for Financial Sentiment Classification")

tab1, tab2 = st.tabs(["Live Demo", "Results Dashboard"])
with tab1:
    live_demo_tab()
with tab2:
    results_dashboard_tab()
